### PR TITLE
feature: add battery charge and discharge power (undocumented register)

### PR DESCRIPTION
**Pull request by cottiAC**
This will receive the undocumented (holding) registers for battery charge/discharge power.

### CODE REVIEW

**Comment by bohdan-s** [comment]
There are a HEAP of undocumented registers in the 32xxx - 34xxx range.
What are we create a separate undocumented registers file and a toggle to enable them?
I think the main "app" should be as close to official as possible out of the box.
Thoughts?

**Comment by cottiAC** [comment]
I like the idea with new flag. But then we would need the flag for the start/range part too? 
Or do we just run over all ranges and only if some of the registers hits, we are doing the actual request?

**Comment by michbeck100** [comment]
I was already thinking of extending the config to add some additional registers. This would be merged with the default registers on startup. This way everybody could have his own custom registers , too. But multiple files would be ok, too.

**Comment by michbeck100** [comment]
I tried your changes on my SH10RT (non v112). Unfortunately the value for `battery_max_charge_power` (33046) show 0 W for me, but in iSolarCloud I can see that it's configured to be 5000 W. `battery_max_discharge_power` is working and show the correct value.

**Comment by cottiAC** [comment]
@michbeck100 - you are right. The register was off by one. Corrected

**Comment by bohdan-s** [comment]
Merged into v0.5.2

**Pull request closed without merging**
